language: python

python:
  - "3.6"

env:
  - DJANGO=2.0

install:
  - pip install "Django>=$DJANGO,<${DJANGO}.99"

script:
- "django-admin.py test django_otp_cache.tests --settings=test_settings --pythonpath=."
